spring:
  application:
    name: "kafka-event-consumer"
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        "[spring.json.trusted.packages]": "dev.zsebel.kafka.domain"
      group-id: "kafka-demo-group1"

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  server:
    port: 8081